INSERT INTO HU_CAT_MONEDA (NUM_CIA, CLAVE_MONEDA, DESCRIPCION, SIMBOLO, ABREVIACION,MONEDA_CORRIENTE,ESTATUS)
VALUES (1, 'MXN', 'MONEDA NACIONAL MEXICANA', '$','MN','S','A');

INSERT INTO HU_CAT_MONEDA (NUM_CIA, CLAVE_MONEDA, DESCRIPCION, SIMBOLO, ABREVIACION,MONEDA_CORRIENTE,ESTATUS)
VALUES (2, 'USD', 'MONEDA EXTRANGERA', '$','US','S','A');

INSERT INTO HU_CAT_MONEDA (NUM_CIA, CLAVE_MONEDA, DESCRIPCION, SIMBOLO, ABREVIACION,MONEDA_CORRIENTE,ESTATUS)
VALUES (3, 'CAN', 'MONEDA EXTRANGERA CANADIENCE', '$','CAN','N','A');
