INSERT INTO HU_CAT_MONEDA (CLAVE_MONEDA, DESCRIPCION, SIMBOLO, ABREVIACION,MONEDA_CORRIENTE,ESTATUS)
VALUES ('MXN', 'MONEDA NACIONAL MEXICANA', '$','MN','S','A');

INSERT INTO HU_CAT_MONEDA (CLAVE_MONEDA, DESCRIPCION, SIMBOLO, ABREVIACION,MONEDA_CORRIENTE,ESTATUS)
VALUES ('USD', 'MONEDA EXTRANGERA', '$','US','S','A');

INSERT INTO HU_CAT_MONEDA (CLAVE_MONEDA, DESCRIPCION, SIMBOLO, ABREVIACION,MONEDA_CORRIENTE,ESTATUS)
VALUES ('CAN', 'MONEDA EXTRANGERA CANADIENCE', '$','CAN','N','A');

CREATE SEQUENCE my_sequence START WITH (SELECT MAX(NUM_CIA) FROM HU_CAT_MONEDA) + 1;
