DROP TABLE IF EXISTS HU_CAT_MONEDA;


CREATE TABLE HU_CAT_MONEDA(
    NUM_CIA NUMBER(4),
    CLAVE_MONEDA  NVARCHAR2(3),
    DESCRIPCION NVARCHAR2(30),
    SIMBOLO NVARCHAR2(5),
    ABREVIACION NVARCHAR2(5),
    MONEDA_CORRIENTE NVARCHAR2(1),
    ESTATUS NVARCHAR2(1),
    CONSTRAINT NUM_CIA_PK PRIMARY KEY (NUM_CIA),
    CONSTRAINT CLAVE_MONEDA_PK PRIMARY KEY (CLAVE_MONEDA)
);

